services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
      POSTGRES_DB: ranimdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: